export const ADD_ORDER_START = "ADD_ORDER_START";
export const ADD_ORDER_SUCCESS = "ADD_ORDER_SUCCESS";
export const ADD_ORDER_ERROR = "ADD_ORDER_ERROR";

export const LOAD_ORDER_BY_ID_START = "LOAD_ORDER_BY_ID_START";
export const LOAD_ORDER_BY_ID_SUCCESS = "LOAD_ORDER_BY_ID_SUCCESS";
export const LOAD_ORDER_BY_ID_ERROR = "LOAD_ORDER_BY_ID_ERROR";
