export const LOAD_PRODUCTS_REQUEST = "LOAD_PRODUCTS_REQUEST";
export const LOAD_PRODUCTS_SUCCESS = "LOAD_PRODUCTS_SUCCESS";
export const LOAD_PRODUCTS_FAILURE = "LOAD_PRODUCTS_FAILURE";

export const LOAD_PRODUCT_BY_SLUG_REQUEST = "LOAD_PRODUCT_BY_SLUG_REQUEST";
export const LOAD_PRODUCT_BY_SLUG_SUCCESS = "LOAD_PRODUCT_BY_SLUG_SUCCESS";
export const LOAD_PRODUCT_BY_SLUG_FAILURE = "LOAD_PRODUCT_BY_SLUG_FAILURE";
